version: '3.6'

volumes:
    redis:
services:
    redis_server:
        image: redis
        restart: always
        volumes:     
            - redis:/data
        deploy:
            resources:
                limits:
                    cpus: '0.10'
                    memory: 128M
    python_server:
        image: byond:18
        restart: always
        ports:
            - ${HOST_PORT}:${CONTAINER_PORT}
        environment:
            REDIS_HOST: redis_server
            REDIS_PORT: 6379
            BIND_PORT: ${CONTAINER_PORT}
        depends_on:
            - redis_server
        deploy:
            resources:
                limits:
                    cpus: '0.20'
                    memory: 512M
        healthcheck:
            test: ["CMD", "curl", "-f", "http://python_server:${CONTAINER_PORT}/"]
            interval: 5s
            timeout: 10s
            retries: 3